# Generated by Django 2.2.1 on 2019-05-12 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0002_perfil'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
